services:
  app:
    image: 120569644879.dkr.ecr.ap-south-1.amazonaws.com/nilanshu-test/backend:v0.2
    networks:
      - public
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8000/playground/health"]
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 10s
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.app.rule=Host(`app.nilanshu.xyz`)"
        - "traefik.http.routers.app.service=app"
        - "traefik.http.services.app.loadbalancer.server.port=8000"
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  # Celery Worker
  celery:
    image: 120569644879.dkr.ecr.ap-south-1.amazonaws.com/nilanshu-test/backend:v0.2
    depends_on:
      - app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A myproject worker --loglevel=info
    networks:
      - public

  # Celery Beat (Optional, for scheduled tasks)
  celery_beat:
    image: 120569644879.dkr.ecr.ap-south-1.amazonaws.com/nilanshu-test/backend:v0.2
    depends_on:
      - app
      - celery
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A myproject beat --loglevel=info
    networks:
      - public

networks:
  public:
    external: true
