services:
  agent:
    image: portainer/agent:2.21.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:2.21.5
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - agent_network
      - public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(`portainer.me.dev`)"
        - "traefik.http.routers.portainer.service=portainer"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  
  traefik:
    image: traefik:v3.3
    ports:
      - 80:80
      - 443:443
      # - 8080:8080
    networks:
      - public
    command:
      - "--entryPoints.http.address=:80"
      - "--entryPoints.https.address=:443"
      - "--ping=true"
      - "--log.level=DEBUG"
      - "--providers.swarm=true"
      - "--providers.swarm.network=public"
      - "--api.insecure=true"
      - "--api.dashboard=true"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.test-compress.compress=true"
        - "traefik.http.routers.dashboard.rule=Host(`console.localhost`)"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
        - "traefik.http.routers.ping.rule=Path(`/ping`)"
        - "traefik.http.routers.ping.service=ping@internal"
        - "traefik.http.services.ping.loadbalancer.server.port=8080"
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whoami:
    image: traefik/whoami:v1.10
    networks:
      - public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  agent_network:
    driver: overlay
    attachable: true
  public:
    driver: overlay
    attachable: true

