services:
  # PostgreSQL Database
  postgres:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: brobazaar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - public

  # Elasticsearch
  elasticsearch:
      container_name: elasticsearch
      image: elasticsearch:7.14.2
      environment:
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
        - bootstrap.memory_lock=true
      ulimits:
        memlock:
                soft: -1
                hard: -1
      networks:
        - public
      volumes:
        - es_volume:/usr/share/elasticsearch/data/
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.elasticsearch.rule=Host(`es.nilanshu.xyz`)"
        - "traefik.http.services.elasticsearch.loadbalancer.server.port=9200"
        - "traefik.http.routers.elasticsearch.entrypoints=web"

  # Redis for Celery
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - public
    volumes:
      - redis_data:/data

  # Celery Worker
  celery:
    build:
      context: .
    container_name: celery
    restart: always
    depends_on:
      - redis
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    command: celery -A myproject worker --loglevel=info
    networks:
      - public

  # Celery Beat (Optional, for scheduled tasks)
  celery_beat:
    build:
      context: .
    container_name: celery_beat
    restart: always
    depends_on:
      - redis
      - celery
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    command: celery -A myproject beat --loglevel=info
    networks:
      - public

  # Shlink (URL Shortener)
  shlink:
    image: shlinkio/shlink:4.2-roadrunner
    container_name: shlink
    restart: always
    depends_on:
      - postgres
    environment:
      - DEFAULT_DOMAIN: http://short.nilanshu.xyz
      - DB_DRIVER: postgres
      - DB_HOST: postgres
      - DB_PORT: 5432
      - DB_USER: root
      - DB_PASSWORD: root
      - DB_NAME: mydatabase
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.shlink.loadbalancer.server.port=8080"
    networks:
      - public

  # Shlink Web Client
  shlink_web:
    image: shlinkio/shlink-web-client:stable
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shlink_web.rule=Host(`short.nilanshu.xyz`)"
      - "traefik.http.services.shlink_web.loadbalancer.server.port=80"
      - "traefik.http.routers.shlink_web.entrypoints=web"
    networks:
      - public

  # Nginx Reverse Proxy
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shlink_web.rule=Host(`crm.nilanshu.xyz`)"
      - "traefik.http.services.shlink_web.loadbalancer.server.port=80"
      - "traefik.http.routers.shlink_web.entrypoints=web"
    networks:
      - public

volumes:
  postgres_data:
  esdata:
  redis_data:
